export const dynamic = "force-dynamic"
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { getCurrentUser } from "./actions/getCurrentUser";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "@/providers/ReduxProvider";
import Footer from "@/components/footer/Footer";
import { BasketContextProvider } from "@/hooks/useBasket";
import { WishlistContextProvider } from "@/hooks/useWishlist";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <BasketContextProvider>
            <WishlistContextProvider>
              <Navbar currentUser={currentUser} />
              <Toaster position="top-center" reverseOrder={false} />
              {children}
              <Footer />
            </WishlistContextProvider>
          </BasketContextProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
